import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MONGODB_URI = os.getenv("MONGODB_URI")
FINE_TUNE_SYMPTOM_MODEL = os.getenv("FINE_TUNE_SYMPTOM_MODEL")
FINE_TUNE_EFCY_MODEL = os.getenv("FINE_TUNE_EFCY_MODEL")
FINE_TUNE_USEMETHOD_MODEL = os.getenv("FINE_TUNE_USEMETHOD_MODEL")
FINE_TUNE_ATPN_MODEL = os.getenv("FINE_TUNE_ATPN_MODEL")
PURE_FINE_TUNE_EFCY_MODEL = os.getenv("PURE_FINE_TUNE_EFCY_MODEL")
FLASK_SECRET_KEY = os.getenv("FLASK_SECRET_KEY")
REDIS_HOST =  os.getenv("REDIS_HOST")
REDIS_PORT =  os.getenv("REDIS_PORT")
REDIS_PASSWORD = os.getenv ("REDIS_PASSWORD")